# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

puts "Insertion of Ingredient data..."
puts "--------------------------------------"


Ingredient.destroy_all
puts "Ingredient database cleared."

ingredients_list = [
  "Table salt",
  "Sea salt",
  "Kosher salt",
  "Black pepper (ground)",
  "Black pepper (whole)",
  "White pepper",
  "Cayenne pepper",
  "Chili flakes",
  "Olive oil (Extra Virgin)",
  "Olive oil (Virgin)",
  "Sunflower oil",
  "Canola oil",
  "Coconut oil",
  "Butter",
  "Ghee (Clarified butter)",
  "Vegetable fat",
  "Lard",
  "All-purpose flour (T650)",
  "All-purpose flour (T00)",
  "Medium coarse wheat flour",
  "Coarse wheat flour",
  "Rye flour",
  "Spelt flour",
  "Corn flour",
  "Rice flour",
  "Almond flour",
  "Potato starch",
  "Corn starch",
  "White granulated sugar",
  "Brown sugar",
  "Powdered sugar",
  "Vanilla sugar",
  "Honey",
  "Maple syrup",
  "Agave syrup",
  "Cane sugar",
  "Stevia",
  "Yeast (fresh)",
  "Yeast (dried)",
  "Baking powder",
  "Baking soda",
  "Vanilla extract",
  "Almond extract",
  "Rum",
  "White rice (long-grain)",
  "White rice (short-grain)",
  "Basmati rice",
  "Jasmine rice",
  "Brown rice",
  "Arborio rice",
  "Wild rice",
  "Spaghetti",
  "Penne",
  "Fusilli",
  "Elbow pasta",
  "Lasagna sheets",
  "Egg noodles",
  "Couscous",
  "Gnocchi (Potato dumplings)",
  "Asian noodles (Udon)",
  "Asian noodles (Soba)",
  "Oats (Flakes)",
  "Oats (whole grain)",
  "Quinoa",
  "Buckwheat",
  "Bulgur",
  "Millet",
  "Semolina",
  "Wheat germ",
  "Black beans",
  "Red kidney beans",
  "White beans (Cannellini)",
  "Lentils (Brown)",
  "Lentils (Red)",
  "Lentils (Beluga)",
  "Peas (Dried)",
  "Peas (frozen)",
  "Chickpeas (Dried)",
  "Chickpeas (canned)",
  "Whole milk",
  "Low-fat milk",
  "Cooking cream",
  "Whipping cream",
  "Buttermilk",
  "Condensed milk (Sweetened)",
  "Condensed milk (unsweetened)",
  "Cheddar",
  "Mozzarella",
  "Parmesan (Parmigiano Reggiano)",
  "Gouda",
  "Emmentaler",
  "Feta",
  "Ricotta",
  "Mascarpone",
  "Curd cheese (Tvaroh)",
  "Yogurt (Plain)",
  "Yogurt (Greek)",
  "Sour cream",
  "Crème fraîche",
  "Almond milk",
  "Oat milk",
  "Soy milk",
  "Coconut milk (Canned)",
  "Coconut milk (Carton)",
  "Tofu (Firm)",
  "Tofu (Silken)",
  "Plant-based cream",
  "Beef (Ground)",
  "Beef (Round/Steak)",
  "Beef (Tenderloin)",
  "Veal",
  "Pork tenderloin",
  "Bacon",
  "Ham",
  "Sausage",
  "Hot dogs",
  "Chicken breast",
  "Chicken thighs",
  "Turkey meat",
  "Duck breast",
  "Eggs (Chicken)",
  "Eggs (Quail)",
  "Salmon",
  "Tuna (Fresh)",
  "Tuna (canned)",
  "Cod",
  "Sardines",
  "Shrimp",
  "Mussels",
  "Crab",
  "Onion (Yellow)",
  "Onion (Red)",
  "Shallot",
  "Garlic",
  "Leek",
  "Carrot",
  "Celery (Root)",
  "Celery (Stalk)",
  "Parsley root",
  "Radish",
  "Tomatoes (Fresh)",
  "Tomatoes (canned)",
  "Tomatoes (sun-dried)",
  "Bell pepper (Colored)",
  "Pepper (Chili)",
  "Cucumbers",
  "Pumpkin (Hokkaido)",
  "Pumpkin (Butternut)",
  "Eggplant",
  "Corn",
  "Mushrooms (Champignons)",
  "Mushrooms (Wild/Forest)",
  "Mushrooms (dried)",
  "Spinach",
  "Kale",
  "Brussels sprouts",
  "Lettuce",
  "Broccoli",
  "Cauliflower",
  "Cabbage (White)",
  "Cabbage (Red)",
  "Sauerkraut (Sour Cabbage)",
  "Apples",
  "Bananas",
  "Lemons",
  "Limes",
  "Oranges",
  "Grapes",
  "Strawberries",
  "Raspberries",
  "Blueberries",
  "Mango",
  "Avocado",
  "Pineapple",
  "Dates",
  "Raisins",
  "Figs",
  "Cranberries (Dried)",
  "Basil",
  "Oregano",
  "Thyme",
  "Rosemary",
  "Parsley",
  "Dill",
  "Chives",
  "Mint",
  "Cilantro (leaves)",
  "Curry powder",
  "Chili powder",
  "Garam Masala",
  "Italian herbs",
  "Ras el hanout",
  "Chinese five-spice powder",
  "Caraway (Whole)",
  "Caraway (ground)",
  "Paprika (Sweet)",
  "Paprika (Smoked)",
  "Paprika (Hot/Spicy)",
  "Turmeric",
  "Cinnamon (Whole)",
  "Cinnamon (ground)",
  "Cloves",
  "Nutmeg (Whole)",
  "Nutmeg (ground)",
  "Star anise",
  "Anise",
  "Coriander (seeds)",
  "Ginger (Ground)",
  "Ginger (Fresh)",
  "Bay leaf",
  "Mustard seeds",
  "Saffron",
  "Walnuts",
  "Hazelnuts",
  "Almonds (Sliced)",
  "Almonds (Whole)",
  "Cashews",
  "Peanuts",
  "Pistachios",
  "Pecans",
  "Sesame seeds",
  "Flax seeds",
  "Chia seeds",
  "Pumpkin seeds",
  "Sunflower seeds",
  "Peanut butter (Smooth)",
  "Peanut butter (Crunchy)",
  "Almond butter",
  "Tahini (Sesame paste)",
  "Mustard (Dijon)",
  "Mustard (Whole grain/Smooth)",
  "Ketchup",
  "Mayonnaise",
  "Soy sauce (Light)",
  "Soy sauce (Dark)",
  "Worcestershire sauce",
  "Fish sauce",
  "Hot sauce (Tabasco)",
  "Hot sauce (Sriracha)",
  "White vinegar",
  "Balsamic vinegar",
  "Apple cider vinegar",
  "Sherry vinegar",
  "White cooking wine",
  "Red cooking wine",
  "Chicken broth",
  "Beef broth",
  "Vegetable broth (Cubes)",
  "Vegetable broth (Liquid)",
  "Canned tomatoes (Diced)",
  "Canned tomatoes (Crushed)",
  "Tomato paste",
  "Capers",
  "Olives (Black)",
  "Olives (Green)",
  "Pickles",
  "Roasted peppers (Canned)",
  "Cocoa powder (Unsweetened)",
  "Dark chocolate (Chips)",
  "Dark chocolate (Baking)",
  "Milk chocolate",
  "White chocolate",
  "Chocolate chips",
  "Jam",
  "Marmalade",
  "Gelatin",
  "Agar-agar",
  "Pudding powder"
]

ingredients_list.each do |ingredient_name|
  Ingredient.find_or_create_by!(name: ingredient_name)
end

puts "✅ Inserted #{Ingredient.count} basic ingredients."
puts "--------------------------------------"
puts "Seed data uploaded successfully!"

puts "--------------------------------------"

puts "Insertion of Tag data..."
puts "--------------------------------------"

# Najprv vyčistíme prepojenia, aby sme nenechali "siroty" v databáze
puts "Čistím staré dáta..."
RecipeTag.destroy_all
Tag.destroy_all
puts "Databáza tagov vymazaná."

# Nový, zúžený výber
tags_list = [
  "Breakfast", "Brunch", "Lunch", "Dinner", "Snack", "Side Dish", 
  "Dessert", "Beverage", "Vegan", "Vegetarian", "Gluten-Free",
  "Dairy-Free", "Low-Carb", "High-Protein", "Low-Calorie", "Soup", "Salad"
]

puts "Nahrávam nové tagy..."
tags_list.each do |tag_name|
  Tag.create!(name: tag_name)
end

puts "✅ Úspešne vložených #{Tag.count} tagov."
puts "--------------------------------------"